/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   opcodes.cpp                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: nforay <nforay@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/03/17 18:27:58 by nforay            #+#    #+#             */
/*   Updated: 2022/03/20 01:04:02 by nforay           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "cpu.hpp"

void Cpu::opcode_00() { Cpu::instr_nop(); };
void Cpu::opcode_01() { Cpu::instr_ld(bc); };
void Cpu::opcode_02() { Cpu::instr_ld(Reg::Word(b, c), a); };
void Cpu::opcode_03() { Cpu::instr_inc_nn(bc); };
void Cpu::opcode_04() { Cpu::instr_inc(b); };
void Cpu::opcode_05() { Cpu::instr_dec(b); };
void Cpu::opcode_06() { Cpu::instr_ld(b); };
void Cpu::opcode_07() { Cpu::instr_rlca(); };
void Cpu::opcode_08() { Cpu::instr_ld_nn_sp(); };
void Cpu::opcode_09() { Cpu::instr_add_hl(bc); };
void Cpu::opcode_0A() { Cpu::instr_ld(a, bc); };
void Cpu::opcode_0B() { Cpu::instr_dec_nn(bc); };
void Cpu::opcode_0C() { Cpu::instr_inc(c); };
void Cpu::opcode_0D() { Cpu::instr_dec(c); };
void Cpu::opcode_0E() { Cpu::instr_ld(c); };
void Cpu::opcode_0F() { Cpu::instr_rrca(); };
void Cpu::opcode_10() { Cpu::instr_stop(); };
void Cpu::opcode_11() { Cpu::instr_ld(de); };
void Cpu::opcode_12() { Cpu::instr_ld(Reg::Word(d, e), a); };
void Cpu::opcode_13() { Cpu::instr_inc_nn(de); };
void Cpu::opcode_14() { Cpu::instr_inc(d); };
void Cpu::opcode_15() { Cpu::instr_dec(d); };
void Cpu::opcode_16() { Cpu::instr_ld(d); };
void Cpu::opcode_17() { Cpu::instr_rla(); };
void Cpu::opcode_18() { Cpu::instr_jr(); };
void Cpu::opcode_19() { Cpu::instr_add_hl(de); };
void Cpu::opcode_1A() { Cpu::instr_ld(a, de); };
void Cpu::opcode_1B() { Cpu::instr_dec_nn(de); };
void Cpu::opcode_1C() { Cpu::instr_inc(e); };
void Cpu::opcode_1D() { Cpu::instr_dec(e); };
void Cpu::opcode_1E() { Cpu::instr_ld(e); };
void Cpu::opcode_1F() { Cpu::instr_rra(); };
void Cpu::opcode_20() { Cpu::instr_jr(Cpu::Condition::NZ); };
void Cpu::opcode_21() { Cpu::instr_ld(hl); };
void Cpu::opcode_22() { Cpu::instr_ld_hli_a(a); };
void Cpu::opcode_23() { Cpu::instr_inc_nn(hl); };
void Cpu::opcode_24() { Cpu::instr_inc(h); };
void Cpu::opcode_25() { Cpu::instr_dec(h); };
void Cpu::opcode_26() { Cpu::instr_ld(h); };
void Cpu::opcode_27() { Cpu::instr_daa(); };
void Cpu::opcode_28() { Cpu::instr_jr(Cpu::Condition::Z); };
void Cpu::opcode_29() { Cpu::instr_add_hl(hl); };
void Cpu::opcode_2A() { Cpu::instr_ld_a_hli(a); };
void Cpu::opcode_2B() { Cpu::instr_dec_nn(hl); };
void Cpu::opcode_2C() { Cpu::instr_inc(l); };
void Cpu::opcode_2D() { Cpu::instr_dec(l); };
void Cpu::opcode_2E() { Cpu::instr_ld(l); };
void Cpu::opcode_2F() { Cpu::instr_cpl(); };
void Cpu::opcode_30() { Cpu::instr_jr(Cpu::Condition::NC); };
void Cpu::opcode_31() { Cpu::instr_ld(sp); };
void Cpu::opcode_32() { Cpu::instr_ld_hld_a(a); };
void Cpu::opcode_33() { Cpu::instr_inc_nn(sp); };
void Cpu::opcode_34() { Cpu::instr_inc(hl.get()); };
void Cpu::opcode_35() { Cpu::instr_dec(hl.get()); };
void Cpu::opcode_36() { Cpu::instr_ld(Reg::Word(h, l)); };
void Cpu::opcode_37() { Cpu::instr_scf(); };
void Cpu::opcode_38() { Cpu::instr_jr(Cpu::Condition::C); };
void Cpu::opcode_39() { Cpu::instr_add_hl(sp); };
void Cpu::opcode_3A() { Cpu::instr_ld_a_hld(a); };
void Cpu::opcode_3B() { Cpu::instr_dec_nn(sp); };
void Cpu::opcode_3C() { Cpu::instr_inc(a); };
void Cpu::opcode_3D() { Cpu::instr_dec(a); };
void Cpu::opcode_3E() { Cpu::instr_ld(a); };
void Cpu::opcode_3F() { Cpu::instr_ccf(); };
void Cpu::opcode_40() { Cpu::instr_ld(b, b); };
void Cpu::opcode_41() { Cpu::instr_ld(b, c); };
void Cpu::opcode_43() { Cpu::instr_ld(b, d); };
void Cpu::opcode_42() { Cpu::instr_ld(b, e); };
void Cpu::opcode_44() { Cpu::instr_ld(b, h); };
void Cpu::opcode_45() { Cpu::instr_ld(b, l); };
void Cpu::opcode_46() { Cpu::instr_ld(b, hl); };
void Cpu::opcode_47() { Cpu::instr_ld(b, a); };
void Cpu::opcode_48() { Cpu::instr_ld(c, b); };
void Cpu::opcode_4A() { Cpu::instr_ld(c, c); };
void Cpu::opcode_49() { Cpu::instr_ld(c, d); };
void Cpu::opcode_4B() { Cpu::instr_ld(c, e); };
void Cpu::opcode_4C() { Cpu::instr_ld(c, h); };
void Cpu::opcode_4D() { Cpu::instr_ld(c, l); };
void Cpu::opcode_4E() { Cpu::instr_ld(c, hl); };
void Cpu::opcode_4F() { Cpu::instr_ld(c, a); };
void Cpu::opcode_50() { Cpu::instr_ld(d, b); };
void Cpu::opcode_51() { Cpu::instr_ld(d, c); };
void Cpu::opcode_52() { Cpu::instr_ld(d, d); };
void Cpu::opcode_53() { Cpu::instr_ld(d, e); };
void Cpu::opcode_54() { Cpu::instr_ld(d, h); };
void Cpu::opcode_55() { Cpu::instr_ld(d, l); };
void Cpu::opcode_56() { Cpu::instr_ld(d, hl); };
void Cpu::opcode_57() { Cpu::instr_ld(d, a); };
void Cpu::opcode_58() { Cpu::instr_ld(e, b); };
void Cpu::opcode_59() { Cpu::instr_ld(e, c); };
void Cpu::opcode_5A() { Cpu::instr_ld(e, d); };
void Cpu::opcode_5B() { Cpu::instr_ld(e, e); };
void Cpu::opcode_5C() { Cpu::instr_ld(e, h); };
void Cpu::opcode_5D() { Cpu::instr_ld(e, l); };
void Cpu::opcode_5E() { Cpu::instr_ld(e, hl); };
void Cpu::opcode_5F() { Cpu::instr_ld(e, a); };
void Cpu::opcode_60() { Cpu::instr_ld(h, b); };
void Cpu::opcode_61() { Cpu::instr_ld(h, c); };
void Cpu::opcode_62() { Cpu::instr_ld(h, d); };
void Cpu::opcode_63() { Cpu::instr_ld(h, e); };
void Cpu::opcode_64() { Cpu::instr_ld(h, h); };
void Cpu::opcode_65() { Cpu::instr_ld(h, l); };
void Cpu::opcode_66() { Cpu::instr_ld(h, hl); };
void Cpu::opcode_67() { Cpu::instr_ld(h, a); };
void Cpu::opcode_68() { Cpu::instr_ld(l, b); };
void Cpu::opcode_69() { Cpu::instr_ld(l, c); };
void Cpu::opcode_6A() { Cpu::instr_ld(l, d); };
void Cpu::opcode_6B() { Cpu::instr_ld(l, e); };
void Cpu::opcode_6C() { Cpu::instr_ld(l, h); };
void Cpu::opcode_6D() { Cpu::instr_ld(l, l); };
void Cpu::opcode_6E() { Cpu::instr_ld(l, hl); };
void Cpu::opcode_6F() { Cpu::instr_ld(l, a); };
void Cpu::opcode_70() { Cpu::instr_ld(Reg::Word(h, l), b); };
void Cpu::opcode_71() { Cpu::instr_ld(Reg::Word(h, l), c); };
void Cpu::opcode_72() { Cpu::instr_ld(Reg::Word(h, l), d); };
void Cpu::opcode_73() { Cpu::instr_ld(Reg::Word(h, l), e); };
void Cpu::opcode_74() { Cpu::instr_ld(Reg::Word(h, l), h); };
void Cpu::opcode_75() { Cpu::instr_ld(Reg::Word(h, l), l); };
void Cpu::opcode_76() { Cpu::instr_halt(); };
void Cpu::opcode_77() { Cpu::instr_ld(Reg::Word(h, l), a); };
void Cpu::opcode_78() { Cpu::instr_ld(a, b); };
void Cpu::opcode_79() { Cpu::instr_ld(a, c); };
void Cpu::opcode_7A() { Cpu::instr_ld(a, d); };
void Cpu::opcode_7B() { Cpu::instr_ld(a, e); };
void Cpu::opcode_7C() { Cpu::instr_ld(a, h); };
void Cpu::opcode_7D() { Cpu::instr_ld(a, l); };
void Cpu::opcode_7E() { Cpu::instr_ld(a, hl); };
void Cpu::opcode_7F() { Cpu::instr_ld(a, a); };
void Cpu::opcode_80() { Cpu::instr_add(b); };
void Cpu::opcode_81() { Cpu::instr_add(c); };
void Cpu::opcode_82() { Cpu::instr_add(d); };
void Cpu::opcode_83() { Cpu::instr_add(e); };
void Cpu::opcode_84() { Cpu::instr_add(h); };
void Cpu::opcode_85() { Cpu::instr_add(l); };
void Cpu::opcode_86() { Cpu::instr_add(hl.get()); };
void Cpu::opcode_87() { Cpu::instr_add(a); };
void Cpu::opcode_88() { Cpu::instr_adc(b); };
void Cpu::opcode_89() { Cpu::instr_adc(c); };
void Cpu::opcode_8A() { Cpu::instr_adc(d); };
void Cpu::opcode_8B() { Cpu::instr_adc(e); };
void Cpu::opcode_8C() { Cpu::instr_adc(h); };
void Cpu::opcode_8D() { Cpu::instr_adc(l); };
void Cpu::opcode_8E() { Cpu::instr_adc(hl.get()); };
void Cpu::opcode_8F() { Cpu::instr_adc(a); };
void Cpu::opcode_90() { Cpu::instr_sub(b); };
void Cpu::opcode_92() { Cpu::instr_sub(c); };
void Cpu::opcode_91() { Cpu::instr_sub(d); };
void Cpu::opcode_93() { Cpu::instr_sub(e); };
void Cpu::opcode_94() { Cpu::instr_sub(h); };
void Cpu::opcode_95() { Cpu::instr_sub(l); };
void Cpu::opcode_96() { Cpu::instr_sub(hl.get()); };
void Cpu::opcode_97() { Cpu::instr_sub(a); };
void Cpu::opcode_98() { Cpu::instr_sbc(b); };
void Cpu::opcode_99() { Cpu::instr_sbc(c); };
void Cpu::opcode_9A() { Cpu::instr_sbc(d); };
void Cpu::opcode_9B() { Cpu::instr_sbc(e); };
void Cpu::opcode_9C() { Cpu::instr_sbc(h); };
void Cpu::opcode_9D() { Cpu::instr_sbc(l); };
void Cpu::opcode_9E() { Cpu::instr_sbc(hl.get()); };
void Cpu::opcode_9F() { Cpu::instr_sbc(a); };
void Cpu::opcode_A0() { Cpu::instr_and(b); };
void Cpu::opcode_A1() { Cpu::instr_and(c); };
void Cpu::opcode_A2() { Cpu::instr_and(d); };
void Cpu::opcode_A3() { Cpu::instr_and(e); };
void Cpu::opcode_A4() { Cpu::instr_and(h); };
void Cpu::opcode_A5() { Cpu::instr_and(l); };
void Cpu::opcode_A6() { Cpu::instr_and(hl.get()); };
void Cpu::opcode_A7() { Cpu::instr_and(a); };
void Cpu::opcode_A8() { Cpu::instr_xor(b); };
void Cpu::opcode_A9() { Cpu::instr_xor(c); };
void Cpu::opcode_AA() { Cpu::instr_xor(d); };
void Cpu::opcode_AB() { Cpu::instr_xor(e); };
void Cpu::opcode_AC() { Cpu::instr_xor(h); };
void Cpu::opcode_AD() { Cpu::instr_xor(l); };
void Cpu::opcode_AE() { Cpu::instr_xor(hl.get()); };
void Cpu::opcode_AF() { Cpu::instr_xor(a); };
void Cpu::opcode_B0() { Cpu::instr_or(b); };
void Cpu::opcode_B1() { Cpu::instr_or(c); };
void Cpu::opcode_B2() { Cpu::instr_or(d); };
void Cpu::opcode_B3() { Cpu::instr_or(e); };
void Cpu::opcode_B4() { Cpu::instr_or(h); };
void Cpu::opcode_B5() { Cpu::instr_or(l); };
void Cpu::opcode_B6() { Cpu::instr_or(hl.get()); };
void Cpu::opcode_B7() { Cpu::instr_or(a); };
void Cpu::opcode_B8() { Cpu::instr_cp(b); };
void Cpu::opcode_B9() { Cpu::instr_cp(c); };
void Cpu::opcode_BA() { Cpu::instr_cp(d); };
void Cpu::opcode_BB() { Cpu::instr_cp(e); };
void Cpu::opcode_BC() { Cpu::instr_cp(h); };
void Cpu::opcode_BD() { Cpu::instr_cp(l); };
void Cpu::opcode_BE() { Cpu::instr_cp(hl.get()); };
void Cpu::opcode_BF() { Cpu::instr_cp(a); };
void Cpu::opcode_C0() { Cpu::instr_ret(Cpu::Condition::NZ); };
void Cpu::opcode_C1() { Cpu::instr_pop_nn(bc); };
void Cpu::opcode_C2() { Cpu::instr_jp(Cpu::Condition::NZ); };
void Cpu::opcode_C3() { Cpu::instr_jp(); };
void Cpu::opcode_C4() { Cpu::instr_call(Cpu::Condition::NZ); };
void Cpu::opcode_C5() { Cpu::instr_push_nn(bc); };
void Cpu::opcode_C6() { Cpu::instr_add_n(); };
void Cpu::opcode_C7() { Cpu::instr_rst(0x00); };
void Cpu::opcode_C8() { Cpu::instr_ret(Cpu::Condition::Z); };
void Cpu::opcode_C9() { Cpu::instr_ret(); };
void Cpu::opcode_CA() { Cpu::instr_jp(Cpu::Condition::Z); };
void Cpu::opcode_CB(){};
void Cpu::opcode_CC() { Cpu::instr_call(Cpu::Condition::Z); };
void Cpu::opcode_CD() { Cpu::instr_call(); };
void Cpu::opcode_CE() { Cpu::instr_adc_n(); };
void Cpu::opcode_CF() { Cpu::instr_rst(0x08); };
void Cpu::opcode_D0() { Cpu::instr_ret(Cpu::Condition::NC); };
void Cpu::opcode_D1() { Cpu::instr_pop_nn(de); };
void Cpu::opcode_D2() { Cpu::instr_jp(Cpu::Condition::NC); };
void Cpu::opcode_D3(){}; // illegal opcode
void Cpu::opcode_D4() { Cpu::instr_call(Cpu::Condition::NC); };
void Cpu::opcode_D5() { Cpu::instr_push_nn(de); };
void Cpu::opcode_D6() { Cpu::instr_sub_n(); };
void Cpu::opcode_D7() { Cpu::instr_rst(0x10); };
void Cpu::opcode_D8() { Cpu::instr_ret(Cpu::Condition::C); };
void Cpu::opcode_D9() { Cpu::instr_reti(); };
void Cpu::opcode_DA() { Cpu::instr_jp(Cpu::Condition::C); };
void Cpu::opcode_DB(){}; // illegal opcode
void Cpu::opcode_DC() { Cpu::instr_call(Cpu::Condition::C); };
void Cpu::opcode_DD(){}; // illegal opcode
void Cpu::opcode_DE() { Cpu::instr_sbc_n(); };
void Cpu::opcode_DF() { Cpu::instr_rst(0x18); };
void Cpu::opcode_E0() { Cpu::instr_ld_n_a(a); };
void Cpu::opcode_E1() { Cpu::instr_pop_nn(hl); };
void Cpu::opcode_E2() { Cpu::instr_ld_c_a(c, a); };
void Cpu::opcode_E3(){}; // illegal opcode
void Cpu::opcode_E4(){}; // illegal opcode
void Cpu::opcode_E5() { Cpu::instr_push_nn(hl); };
void Cpu::opcode_E6() { Cpu::instr_and_n(); };
void Cpu::opcode_E7() { Cpu::instr_rst(0x20); };
void Cpu::opcode_E8() { Cpu::instr_add_sp_n(); };
void Cpu::opcode_E9() { Cpu::instr_jp(hl); };
void Cpu::opcode_EA() { Cpu::instr_ld_nn_to(a); };
void Cpu::opcode_EB(){}; // illegal opcode
void Cpu::opcode_EC(){}; // illegal opcode
void Cpu::opcode_ED(){}; // illegal opcode
void Cpu::opcode_EE() { Cpu::instr_xor_n(); };
void Cpu::opcode_EF() { Cpu::instr_rst(0x28); };
void Cpu::opcode_F0() { Cpu::instr_ld_a_n(a); };
void Cpu::opcode_F1() { Cpu::instr_pop_nn(af); };
void Cpu::opcode_F2() { Cpu::instr_ld_a_c(a, c); };
void Cpu::opcode_F3() { Cpu::instr_di(); };
void Cpu::opcode_F4(){}; // illegal opcode
void Cpu::opcode_F5() { Cpu::instr_push_nn(af); };
void Cpu::opcode_F6() { Cpu::instr_or_n(); };
void Cpu::opcode_F7() { Cpu::instr_rst(0x30); };
void Cpu::opcode_F8() { Cpu::instr_ld_hl_sp_n(); };
void Cpu::opcode_F9() { Cpu::instr_ld(sp, hl); };
void Cpu::opcode_FA() { Cpu::instr_ld_nn_from(a); };
void Cpu::opcode_FB() { Cpu::instr_di(); };
void Cpu::opcode_FC(){}; // illegal opcode
void Cpu::opcode_FD(){}; // illegal opcode
void Cpu::opcode_FE() { Cpu::instr_cp_n(); };
void Cpu::opcode_FF() { Cpu::instr_rst(0x38); };

void Cpu::opcode_CB_00() { Cpu::instr_rlc(b); };
void Cpu::opcode_CB_01() { Cpu::instr_rlc(c); };
void Cpu::opcode_CB_02() { Cpu::instr_rlc(d); };
void Cpu::opcode_CB_03() { Cpu::instr_rlc(e); };
void Cpu::opcode_CB_04() { Cpu::instr_rlc(h); };
void Cpu::opcode_CB_05() { Cpu::instr_rlc(l); };
void Cpu::opcode_CB_06() { Cpu::instr_rlc(hl.get()); };
void Cpu::opcode_CB_07() { Cpu::instr_rlc(a); };
void Cpu::opcode_CB_08() { Cpu::instr_rrc(b); };
void Cpu::opcode_CB_09() { Cpu::instr_rrc(c); };
void Cpu::opcode_CB_0A() { Cpu::instr_rrc(d); };
void Cpu::opcode_CB_0B() { Cpu::instr_rrc(e); };
void Cpu::opcode_CB_0C() { Cpu::instr_rrc(h); };
void Cpu::opcode_CB_0D() { Cpu::instr_rrc(l); };
void Cpu::opcode_CB_0E() { Cpu::instr_rrc(hl.get()); };
void Cpu::opcode_CB_0F() { Cpu::instr_rrc(a); };
void Cpu::opcode_CB_10() { Cpu::instr_rl(b); };
void Cpu::opcode_CB_11() { Cpu::instr_rl(c); };
void Cpu::opcode_CB_12() { Cpu::instr_rl(d); };
void Cpu::opcode_CB_13() { Cpu::instr_rl(e); };
void Cpu::opcode_CB_14() { Cpu::instr_rl(h); };
void Cpu::opcode_CB_15() { Cpu::instr_rl(l); };
void Cpu::opcode_CB_16() { Cpu::instr_rl(hl.get()); };
void Cpu::opcode_CB_17() { Cpu::instr_rl(a); };
void Cpu::opcode_CB_18() { Cpu::instr_rr(b); };
void Cpu::opcode_CB_19() { Cpu::instr_rr(c); };
void Cpu::opcode_CB_1A() { Cpu::instr_rr(d); };
void Cpu::opcode_CB_1B() { Cpu::instr_rr(e); };
void Cpu::opcode_CB_1C() { Cpu::instr_rr(h); };
void Cpu::opcode_CB_1D() { Cpu::instr_rr(l); };
void Cpu::opcode_CB_1E() { Cpu::instr_rr(hl.get()); };
void Cpu::opcode_CB_1F() { Cpu::instr_rr(a); };
void Cpu::opcode_CB_20() { Cpu::instr_sla(b); };
void Cpu::opcode_CB_21() { Cpu::instr_sla(c); };
void Cpu::opcode_CB_22() { Cpu::instr_sla(d); };
void Cpu::opcode_CB_23() { Cpu::instr_sla(e); };
void Cpu::opcode_CB_24() { Cpu::instr_sla(h); };
void Cpu::opcode_CB_25() { Cpu::instr_sla(l); };
void Cpu::opcode_CB_26() { Cpu::instr_sla(hl.get()); };
void Cpu::opcode_CB_27() { Cpu::instr_sla(a); };
void Cpu::opcode_CB_28() { Cpu::instr_sra(b); };
void Cpu::opcode_CB_29() { Cpu::instr_sra(c); };
void Cpu::opcode_CB_2A() { Cpu::instr_sra(d); };
void Cpu::opcode_CB_2B() { Cpu::instr_sra(e); };
void Cpu::opcode_CB_2C() { Cpu::instr_sra(h); };
void Cpu::opcode_CB_2D() { Cpu::instr_sra(l); };
void Cpu::opcode_CB_2E() { Cpu::instr_sra(hl.get()); };
void Cpu::opcode_CB_2F() { Cpu::instr_sra(a); };
void Cpu::opcode_CB_30() { instr_swap(b); };
void Cpu::opcode_CB_31() { instr_swap(c); };
void Cpu::opcode_CB_32() { instr_swap(d); };
void Cpu::opcode_CB_33() { instr_swap(e); };
void Cpu::opcode_CB_34() { instr_swap(h); };
void Cpu::opcode_CB_35() { instr_swap(l); };
void Cpu::opcode_CB_36() { instr_swap(hl.get()); };
void Cpu::opcode_CB_37() { instr_swap(a); };
void Cpu::opcode_CB_38() { Cpu::instr_srl(b); };
void Cpu::opcode_CB_39() { Cpu::instr_srl(c); };
void Cpu::opcode_CB_3A() { Cpu::instr_srl(d); };
void Cpu::opcode_CB_3B() { Cpu::instr_srl(e); };
void Cpu::opcode_CB_3C() { Cpu::instr_srl(h); };
void Cpu::opcode_CB_3D() { Cpu::instr_srl(l); };
void Cpu::opcode_CB_3E() { Cpu::instr_srl(hl.get()); };
void Cpu::opcode_CB_3F() { Cpu::instr_srl(a); };
void Cpu::opcode_CB_40() { Cpu::instr_bit(0, b); };
void Cpu::opcode_CB_41() { Cpu::instr_bit(0, c); };
void Cpu::opcode_CB_42() { Cpu::instr_bit(0, d); };
void Cpu::opcode_CB_43() { Cpu::instr_bit(0, e); };
void Cpu::opcode_CB_44() { Cpu::instr_bit(0, h); };
void Cpu::opcode_CB_45() { Cpu::instr_bit(0, l); };
void Cpu::opcode_CB_46() { Cpu::instr_bit(0, hl.get()); };
void Cpu::opcode_CB_47() { Cpu::instr_bit(0, a); };
void Cpu::opcode_CB_48() { Cpu::instr_bit(1, b); };
void Cpu::opcode_CB_49() { Cpu::instr_bit(1, c); };
void Cpu::opcode_CB_4A() { Cpu::instr_bit(1, d); };
void Cpu::opcode_CB_4B() { Cpu::instr_bit(1, e); };
void Cpu::opcode_CB_4C() { Cpu::instr_bit(1, h); };
void Cpu::opcode_CB_4D() { Cpu::instr_bit(1, l); };
void Cpu::opcode_CB_4E() { Cpu::instr_bit(1, hl.get()); };
void Cpu::opcode_CB_4F() { Cpu::instr_bit(1, a); };
void Cpu::opcode_CB_50() { Cpu::instr_bit(2, b); };
void Cpu::opcode_CB_51() { Cpu::instr_bit(2, c); };
void Cpu::opcode_CB_52() { Cpu::instr_bit(2, d); };
void Cpu::opcode_CB_53() { Cpu::instr_bit(2, e); };
void Cpu::opcode_CB_54() { Cpu::instr_bit(2, h); };
void Cpu::opcode_CB_55() { Cpu::instr_bit(2, l); };
void Cpu::opcode_CB_56() { Cpu::instr_bit(2, hl.get()); };
void Cpu::opcode_CB_57() { Cpu::instr_bit(2, a); };
void Cpu::opcode_CB_58() { Cpu::instr_bit(3, b); };
void Cpu::opcode_CB_59() { Cpu::instr_bit(3, c); };
void Cpu::opcode_CB_5A() { Cpu::instr_bit(3, d); };
void Cpu::opcode_CB_5B() { Cpu::instr_bit(3, e); };
void Cpu::opcode_CB_5C() { Cpu::instr_bit(3, h); };
void Cpu::opcode_CB_5D() { Cpu::instr_bit(3, l); };
void Cpu::opcode_CB_5E() { Cpu::instr_bit(3, hl.get()); };
void Cpu::opcode_CB_5F() { Cpu::instr_bit(3, a); };
void Cpu::opcode_CB_60() { Cpu::instr_bit(4, b); };
void Cpu::opcode_CB_61() { Cpu::instr_bit(4, c); };
void Cpu::opcode_CB_62() { Cpu::instr_bit(4, d); };
void Cpu::opcode_CB_63() { Cpu::instr_bit(4, e); };
void Cpu::opcode_CB_64() { Cpu::instr_bit(4, h); };
void Cpu::opcode_CB_65() { Cpu::instr_bit(4, l); };
void Cpu::opcode_CB_66() { Cpu::instr_bit(4, hl.get()); };
void Cpu::opcode_CB_67() { Cpu::instr_bit(4, a); };
void Cpu::opcode_CB_68() { Cpu::instr_bit(5, b); };
void Cpu::opcode_CB_69() { Cpu::instr_bit(5, c); };
void Cpu::opcode_CB_6A() { Cpu::instr_bit(5, d); };
void Cpu::opcode_CB_6B() { Cpu::instr_bit(5, e); };
void Cpu::opcode_CB_6C() { Cpu::instr_bit(5, h); };
void Cpu::opcode_CB_6D() { Cpu::instr_bit(5, l); };
void Cpu::opcode_CB_6E() { Cpu::instr_bit(5, hl.get()); };
void Cpu::opcode_CB_6F() { Cpu::instr_bit(5, a); };
void Cpu::opcode_CB_70() { Cpu::instr_bit(6, b); };
void Cpu::opcode_CB_71() { Cpu::instr_bit(6, c); };
void Cpu::opcode_CB_72() { Cpu::instr_bit(6, d); };
void Cpu::opcode_CB_73() { Cpu::instr_bit(6, e); };
void Cpu::opcode_CB_74() { Cpu::instr_bit(6, h); };
void Cpu::opcode_CB_75() { Cpu::instr_bit(6, l); };
void Cpu::opcode_CB_76() { Cpu::instr_bit(6, hl.get()); };
void Cpu::opcode_CB_77() { Cpu::instr_bit(6, a); };
void Cpu::opcode_CB_78() { Cpu::instr_bit(7, b); };
void Cpu::opcode_CB_79() { Cpu::instr_bit(7, c); };
void Cpu::opcode_CB_7A() { Cpu::instr_bit(7, d); };
void Cpu::opcode_CB_7B() { Cpu::instr_bit(7, e); };
void Cpu::opcode_CB_7C() { Cpu::instr_bit(7, h); };
void Cpu::opcode_CB_7D() { Cpu::instr_bit(7, l); };
void Cpu::opcode_CB_7E() { Cpu::instr_bit(7, hl.get()); };
void Cpu::opcode_CB_7F() { Cpu::instr_bit(7, a); };
void Cpu::opcode_CB_80() { Cpu::instr_res(0, b); };
void Cpu::opcode_CB_81() { Cpu::instr_res(0, c); };
void Cpu::opcode_CB_82() { Cpu::instr_res(0, d); };
void Cpu::opcode_CB_83() { Cpu::instr_res(0, e); };
void Cpu::opcode_CB_84() { Cpu::instr_res(0, h); };
void Cpu::opcode_CB_85() { Cpu::instr_res(0, l); };
void Cpu::opcode_CB_86() { Cpu::instr_res(0, hl.get()); };
void Cpu::opcode_CB_87() { Cpu::instr_res(0, a); };
void Cpu::opcode_CB_88() { Cpu::instr_res(1, b); };
void Cpu::opcode_CB_89() { Cpu::instr_res(1, c); };
void Cpu::opcode_CB_8A() { Cpu::instr_res(1, d); };
void Cpu::opcode_CB_8B() { Cpu::instr_res(1, e); };
void Cpu::opcode_CB_8C() { Cpu::instr_res(1, h); };
void Cpu::opcode_CB_8D() { Cpu::instr_res(1, l); };
void Cpu::opcode_CB_8E() { Cpu::instr_res(1, hl.get()); };
void Cpu::opcode_CB_8F() { Cpu::instr_res(1, a); };
void Cpu::opcode_CB_90() { Cpu::instr_res(2, b); };
void Cpu::opcode_CB_91() { Cpu::instr_res(2, c); };
void Cpu::opcode_CB_92() { Cpu::instr_res(2, d); };
void Cpu::opcode_CB_93() { Cpu::instr_res(2, e); };
void Cpu::opcode_CB_94() { Cpu::instr_res(2, h); };
void Cpu::opcode_CB_95() { Cpu::instr_res(2, l); };
void Cpu::opcode_CB_96() { Cpu::instr_res(2, hl.get()); };
void Cpu::opcode_CB_97() { Cpu::instr_res(2, a); };
void Cpu::opcode_CB_98() { Cpu::instr_res(3, b); };
void Cpu::opcode_CB_99() { Cpu::instr_res(3, c); };
void Cpu::opcode_CB_9A() { Cpu::instr_res(3, d); };
void Cpu::opcode_CB_9B() { Cpu::instr_res(3, e); };
void Cpu::opcode_CB_9C() { Cpu::instr_res(3, h); };
void Cpu::opcode_CB_9D() { Cpu::instr_res(3, l); };
void Cpu::opcode_CB_9E() { Cpu::instr_res(3, hl.get()); };
void Cpu::opcode_CB_9F() { Cpu::instr_res(3, a); };
void Cpu::opcode_CB_A0() { Cpu::instr_res(4, b); };
void Cpu::opcode_CB_A1() { Cpu::instr_res(4, c); };
void Cpu::opcode_CB_A2() { Cpu::instr_res(4, d); };
void Cpu::opcode_CB_A3() { Cpu::instr_res(4, e); };
void Cpu::opcode_CB_A4() { Cpu::instr_res(4, h); };
void Cpu::opcode_CB_A5() { Cpu::instr_res(4, l); };
void Cpu::opcode_CB_A6() { Cpu::instr_res(4, hl.get()); };
void Cpu::opcode_CB_A7() { Cpu::instr_res(4, a); };
void Cpu::opcode_CB_A8() { Cpu::instr_res(5, b); };
void Cpu::opcode_CB_A9() { Cpu::instr_res(5, c); };
void Cpu::opcode_CB_AA() { Cpu::instr_res(5, d); };
void Cpu::opcode_CB_AB() { Cpu::instr_res(5, e); };
void Cpu::opcode_CB_AC() { Cpu::instr_res(5, h); };
void Cpu::opcode_CB_AD() { Cpu::instr_res(5, l); };
void Cpu::opcode_CB_AE() { Cpu::instr_res(5, hl.get()); };
void Cpu::opcode_CB_AF() { Cpu::instr_res(5, a); };
void Cpu::opcode_CB_B0() { Cpu::instr_res(6, b); };
void Cpu::opcode_CB_B1() { Cpu::instr_res(6, c); };
void Cpu::opcode_CB_B2() { Cpu::instr_res(6, d); };
void Cpu::opcode_CB_B3() { Cpu::instr_res(6, e); };
void Cpu::opcode_CB_B4() { Cpu::instr_res(6, h); };
void Cpu::opcode_CB_B5() { Cpu::instr_res(6, l); };
void Cpu::opcode_CB_B6() { Cpu::instr_res(6, hl.get()); };
void Cpu::opcode_CB_B7() { Cpu::instr_res(6, a); };
void Cpu::opcode_CB_B8() { Cpu::instr_res(7, b); };
void Cpu::opcode_CB_B9() { Cpu::instr_res(7, c); };
void Cpu::opcode_CB_BA() { Cpu::instr_res(7, d); };
void Cpu::opcode_CB_BB() { Cpu::instr_res(7, e); };
void Cpu::opcode_CB_BC() { Cpu::instr_res(7, h); };
void Cpu::opcode_CB_BD() { Cpu::instr_res(7, l); };
void Cpu::opcode_CB_BE() { Cpu::instr_res(7, hl.get()); };
void Cpu::opcode_CB_BF() { Cpu::instr_res(7, a); };
void Cpu::opcode_CB_C0() { Cpu::instr_set(0, b); };
void Cpu::opcode_CB_C1() { Cpu::instr_set(0, c); };
void Cpu::opcode_CB_C2() { Cpu::instr_set(0, d); };
void Cpu::opcode_CB_C3() { Cpu::instr_set(0, e); };
void Cpu::opcode_CB_C4() { Cpu::instr_set(0, h); };
void Cpu::opcode_CB_C5() { Cpu::instr_set(0, l); };
void Cpu::opcode_CB_C6() { Cpu::instr_set(0, hl.get()); };
void Cpu::opcode_CB_C7() { Cpu::instr_set(0, a); };
void Cpu::opcode_CB_C8() { Cpu::instr_set(1, b); };
void Cpu::opcode_CB_C9() { Cpu::instr_set(1, c); };
void Cpu::opcode_CB_CA() { Cpu::instr_set(1, d); };
void Cpu::opcode_CB_CB() { Cpu::instr_set(1, e); };
void Cpu::opcode_CB_CC() { Cpu::instr_set(1, h); };
void Cpu::opcode_CB_CD() { Cpu::instr_set(1, l); };
void Cpu::opcode_CB_CE() { Cpu::instr_set(1, hl.get()); };
void Cpu::opcode_CB_CF() { Cpu::instr_set(1, a); };
void Cpu::opcode_CB_D0() { Cpu::instr_set(2, b); };
void Cpu::opcode_CB_D1() { Cpu::instr_set(2, c); };
void Cpu::opcode_CB_D2() { Cpu::instr_set(2, d); };
void Cpu::opcode_CB_D3() { Cpu::instr_set(2, e); };
void Cpu::opcode_CB_D4() { Cpu::instr_set(2, h); };
void Cpu::opcode_CB_D5() { Cpu::instr_set(2, l); };
void Cpu::opcode_CB_D6() { Cpu::instr_set(2, hl.get()); };
void Cpu::opcode_CB_D7() { Cpu::instr_set(2, a); };
void Cpu::opcode_CB_D8() { Cpu::instr_set(3, b); };
void Cpu::opcode_CB_D9() { Cpu::instr_set(3, c); };
void Cpu::opcode_CB_DA() { Cpu::instr_set(3, d); };
void Cpu::opcode_CB_DB() { Cpu::instr_set(3, e); };
void Cpu::opcode_CB_DC() { Cpu::instr_set(3, h); };
void Cpu::opcode_CB_DD() { Cpu::instr_set(3, l); };
void Cpu::opcode_CB_DE() { Cpu::instr_set(3, hl.get()); };
void Cpu::opcode_CB_DF() { Cpu::instr_set(3, a); };
void Cpu::opcode_CB_E0() { Cpu::instr_set(4, b); };
void Cpu::opcode_CB_E1() { Cpu::instr_set(4, c); };
void Cpu::opcode_CB_E2() { Cpu::instr_set(4, d); };
void Cpu::opcode_CB_E3() { Cpu::instr_set(4, e); };
void Cpu::opcode_CB_E4() { Cpu::instr_set(4, h); };
void Cpu::opcode_CB_E5() { Cpu::instr_set(4, l); };
void Cpu::opcode_CB_E6() { Cpu::instr_set(4, hl.get()); };
void Cpu::opcode_CB_E7() { Cpu::instr_set(4, a); };
void Cpu::opcode_CB_E8() { Cpu::instr_set(5, b); };
void Cpu::opcode_CB_E9() { Cpu::instr_set(5, c); };
void Cpu::opcode_CB_EA() { Cpu::instr_set(5, d); };
void Cpu::opcode_CB_EB() { Cpu::instr_set(5, e); };
void Cpu::opcode_CB_EC() { Cpu::instr_set(5, h); };
void Cpu::opcode_CB_ED() { Cpu::instr_set(5, l); };
void Cpu::opcode_CB_EE() { Cpu::instr_set(5, hl.get()); };
void Cpu::opcode_CB_EF() { Cpu::instr_set(5, a); };
void Cpu::opcode_CB_F0() { Cpu::instr_set(6, b); };
void Cpu::opcode_CB_F1() { Cpu::instr_set(6, c); };
void Cpu::opcode_CB_F2() { Cpu::instr_set(6, d); };
void Cpu::opcode_CB_F3() { Cpu::instr_set(6, e); };
void Cpu::opcode_CB_F4() { Cpu::instr_set(6, h); };
void Cpu::opcode_CB_F5() { Cpu::instr_set(6, l); };
void Cpu::opcode_CB_F6() { Cpu::instr_set(6, hl.get()); };
void Cpu::opcode_CB_F7() { Cpu::instr_set(6, a); };
void Cpu::opcode_CB_F8() { Cpu::instr_set(7, b); };
void Cpu::opcode_CB_F9() { Cpu::instr_set(7, c); };
void Cpu::opcode_CB_FA() { Cpu::instr_set(7, d); };
void Cpu::opcode_CB_FB() { Cpu::instr_set(7, e); };
void Cpu::opcode_CB_FC() { Cpu::instr_set(7, h); };
void Cpu::opcode_CB_FD() { Cpu::instr_set(7, l); };
void Cpu::opcode_CB_FE() { Cpu::instr_set(7, hl.get()); };
void Cpu::opcode_CB_FF() { Cpu::instr_set(7, a); };
